version: 0.2

env:
  parameter-store:
    github_ssh_key: "github_ssh_key"
    k8s_deployment_slack_notification_sns_topic_arn: "k8s_deployment_slack_notification_sns_topic_arn"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "skip"
      # - git config --global pull.rebase false
      # - apt-get update
      # - apt-get -y install jq python3-pip mysql-server libmysqlclient-dev redis-server 
      # - pip3 install --upgrade awscli
      # - redis-server --daemonize yes

  pre_build:
    commands:
      - echo "skip"
      # - mysql -u root -e "DROP DATABASE IF EXISTS superset; CREATE DATABASE superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"	
      # - mysql -u root -e "DROP DATABASE IF EXISTS sqllab_test_db; CREATE DATABASE sqllab_test_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"	
      # - mysql -u root -e "DROP DATABASE IF EXISTS admin_database; CREATE DATABASE admin_database DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"	
      # - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"	
      # - mysql -u root -e "GRANT ALL ON *.* TO 'mysqluser'@'localhost';"
      # - export TIMESTAMP=$(date +"%Y%m%d%H%M%S")
      # - export TAG=$REPOSITORY_BRANCH-v$TIMESTAMP
      # - $(aws ecr get-login --no-include-email)
      # - tox -e py38

  build:
    commands:
      - echo Building API image
      # - bundle package --all
      # - docker build --tag $REPOSITORY_URI:$TAG .

  post_build:
    commands:
      - | 
          echo Pushing new image to ECR 
          docker push $REPOSITORY_URI:$TAG 
          pushd $PWD

          dir=$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)

          mkdir -p tmp

          cd tmp

          echo "Cloning bitpesa Terraform repository"
          echo "============================================"

          git clone git@github.com:bitpesa/bitpesa-terraform.git || true

          popd

          pushd  $PWD
          echo "Test"
          echo "============================================"

          cd tmp/bitpesa-terraform/

          ls

          popd

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
